<?php

namespace SuccessFacileBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuotiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotiteRepository extends EntityRepository
{
}
