<?php

namespace SuccessFacileBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SitunochildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitunochildRepository extends EntityRepository
{
}
