Acceuil:
    path: /
    defaults: { _controller: SuccessFacileBundle:Site:index }

Simulateur:
    path: /simulateur
    defaults: { _controller: SuccessFacileBundle:Calcul:index }

Combien:
    path: /combien
    defaults: { _controller: SuccessFacileBundle:Combien:index }

Quotite:
    path: /quotite
    defaults: { _controller: SuccessFacileBundle:Quotite:index }

recompose:
    path: /simulateur/recompose
    defaults: { _controller: SuccessFacileBundle:Calcul:FORM_ifR }

form_NR:
    path: /simulateur/form_NR
    defaults: { _controller: SuccessFacileBundle:Calcul:Form_NR }

Form_R:
    path: /simulateur/Form_R
    defaults: { _controller: SuccessFacileBundle:Calcul:Form_R }

formpatrimoine:
    path: /simulateur/formpatrimoine
    defaults: { _controller: SuccessFacileBundle:Calcul:Formpatrimoine }

formpourcent:
    path: /simulateur/formpourcent
    defaults: { _controller: SuccessFacileBundle:Calcul:Formpourcent }

Nochild:
    path: /simulateur/Nochild
    defaults: { _controller: SuccessFacileBundle:Calcul:FormNE }

gp:
    path: /simulateur/gp
    defaults: { _controller: SuccessFacileBundle:Calcul:Formgp }

About:
    path: /about
    defaults: { _controller: SuccessFacileBundle:Site:about }

Contact:
    path: /contact
    defaults: { _controller: SuccessFacileBundle:Site:contact }

