Acceuil:
    path: /
    defaults: { _controller: SuccessFacileBundle:Site:index }


Simulateur:
    path: /simulateur
    defaults: { _controller: SuccessFacileBundle:Calcul:index }

Combien:
    path: /combien_tu_raques_batard
    defaults: { _controller: SuccessFacileBundle:Combien:index }

Quotite:
    path: /tu_ne_peux_pas_desheriter_tes_gosses_FDP
    defaults: { _controller: SuccessFacileBundle:Quotite:index }

M_NR:
    path: /simulateur/M_NR
    defaults: { _controller: SuccessFacileBundle:Calcul:M_NR }

M_R:
    path: /simulateur/M_R
    defaults: { _controller: SuccessFacileBundle:Calcul:M_R }

C_NR:
    path: /simulateur/C_NR
    defaults: { _controller: SuccessFacileBundle:Calcul:C_NR }

C_R:
    path: /simulateur/C_R
    defaults: { _controller: SuccessFacileBundle:Calcul:C_R }

V_NR:
    path: /simulateur/V_NR
    defaults: { _controller: SuccessFacileBundle:Calcul:V_NR }

V_R:
    path: /simulateur/V_R
    defaults: { _controller: SuccessFacileBundle:Calcul:V_R }

S_NR:
    path: /simulateur/S_NR
    defaults: { _controller: SuccessFacileBundle:Calcul:S_NR }
S_R:
    path: /simulateur/S_R
    defaults: { _controller: SuccessFacileBundle:Calcul:S_R }

D_NR:
    path: /simulateur/D_NR
    defaults: { _controller: SuccessFacileBundle:Calcul:D_NR }

D_R:
    path: /simulateur/D_R
    defaults: { _controller: SuccessFacileBundle:Calcul:D_R }

P_NR:
    path: /simulateur/P_NR
    defaults: { _controller: SuccessFacileBundle:Calcul:P_NR }

P_R:
    path: /simulateur/P_R
    defaults: { _controller: SuccessFacileBundle:Calcul:P_R }

Ec_NR:
    path: /simulateur/Ec_NR
    defaults: { _controller: SuccessFacileBundle:Calcul:Ec_NR }

Ec_R:
    path: /simulateur/Ec_R
    defaults: { _controller: SuccessFacileBundle:Calcul:Ec_R }

Nochild:
    path: /simulateur/Nochild
    defaults: { _controller: SuccessFacileBundle:Calcul:FormNE }

gp:
    path: /simulateur/
    defaults: { _controller: SuccessFacileBundle:Calcul:Formgp }

About:
    path: /about
    defaults: { _controller: SuccessFacileBundle:Site:about }

Contact:
    path: /contact
    defaults: { _controller: SuccessFacileBundle:Site:contact }

