<?php

namespace Proxies\__CG__\SuccessFacileBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usufruit extends \SuccessFacileBundle\Entity\Usufruit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'id', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'age', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'enfant', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'enfant_conjoint', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'enfant_perso', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'residence', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'epargne', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'autre');
        }

        return array('__isInitialized__', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'id', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'age', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'enfant', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'enfant_conjoint', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'enfant_perso', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'residence', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'epargne', '' . "\0" . 'SuccessFacileBundle\\Entity\\Usufruit' . "\0" . 'autre');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usufruit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge($age)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', array($age));

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', array());

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnfant($enfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnfant', array($enfant));

        return parent::setEnfant($enfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnfant', array());

        return parent::getEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnfantConjoint($enfant_conjoint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnfantConjoint', array($enfant_conjoint));

        return parent::setEnfantConjoint($enfant_conjoint);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnfantConjoint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnfantConjoint', array());

        return parent::getEnfantConjoint();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnfantPerso($enfant_perso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnfantPerso', array($enfant_perso));

        return parent::setEnfantPerso($enfant_perso);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnfantPerso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnfantPerso', array());

        return parent::getEnfantPerso();
    }

    /**
     * {@inheritDoc}
     */
    public function setResidence($residence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResidence', array($residence));

        return parent::setResidence($residence);
    }

    /**
     * {@inheritDoc}
     */
    public function getResidence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResidence', array());

        return parent::getResidence();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpargne($epargne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpargne', array($epargne));

        return parent::setEpargne($epargne);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpargne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpargne', array());

        return parent::getEpargne();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutre($autre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutre', array($autre));

        return parent::setAutre($autre);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutre', array());

        return parent::getAutre();
    }

}
