<?php

namespace Proxies\__CG__\SuccessFacileBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Situnochild extends \SuccessFacileBundle\Entity\Situnochild implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'id', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'maman', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'papa', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'siblings', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'gppaternel', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'gpmaternel');
        }

        return array('__isInitialized__', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'id', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'maman', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'papa', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'siblings', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'gppaternel', '' . "\0" . 'SuccessFacileBundle\\Entity\\Situnochild' . "\0" . 'gpmaternel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Situnochild $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaman($maman)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaman', array($maman));

        return parent::setMaman($maman);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaman()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaman', array());

        return parent::getMaman();
    }

    /**
     * {@inheritDoc}
     */
    public function setPapa($papa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPapa', array($papa));

        return parent::setPapa($papa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPapa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPapa', array());

        return parent::getPapa();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiblings($siblings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiblings', array($siblings));

        return parent::setSiblings($siblings);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiblings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiblings', array());

        return parent::getSiblings();
    }

    /**
     * {@inheritDoc}
     */
    public function setGppaternel($gppaternel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGppaternel', array($gppaternel));

        return parent::setGppaternel($gppaternel);
    }

    /**
     * {@inheritDoc}
     */
    public function getGppaternel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGppaternel', array());

        return parent::getGppaternel();
    }

    /**
     * {@inheritDoc}
     */
    public function setGpmaternel($gpmaternel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGpmaternel', array($gpmaternel));

        return parent::setGpmaternel($gpmaternel);
    }

    /**
     * {@inheritDoc}
     */
    public function getGpmaternel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGpmaternel', array());

        return parent::getGpmaternel();
    }

}
